version: "3.4"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

  backend:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    command: ["sh", "start.sh"]
    ports:
      - 8000:8000
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    depends_on:
      - db

volumes:
  postgres_db_data:
