version: "3.4"

services:
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    env_file:
      - ./.envs/.postgres

volumes:
  postgres_db_data:
